In [1]:
import pandas as pd
obj = pd.Series([1,2,3,4,5])
print(obj)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [2]:
obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
sales = pd.Series([100,200,300,400])
print(sales.values)
print(sales.index)

[100 200 300 400]
RangeIndex(start=0, stop=4, step=1)


In [4]:
sales = pd.Series([100,200,300,400,500], index = ['a','b','c','d','e'])
print(sales)

a    100
b    200
c    300
d    400
e    500
dtype: int64


In [8]:
sales = pd.Series([100,200,300,400,500], index = ['jan','feb','mar','apr','may'])
print(sales)
print(sales.values)
print(sales.index)

jan    100
feb    200
mar    300
apr    400
may    500
dtype: int64
[100 200 300 400 500]
Index(['jan', 'feb', 'mar', 'apr', 'may'], dtype='object')


In [9]:
sales = pd.Series([100,200,300,400,500], index = ['jan','feb','mar','apr','may'], name = "5 mounth series")
print(sales)
print(sales.values)
print(sales.index)

jan    100
feb    200
mar    300
apr    400
may    500
Name: 5 mounth series, dtype: int64
[100 200 300 400 500]
Index(['jan', 'feb', 'mar', 'apr', 'may'], dtype='object')


Canteen data and hold values pervious week

In [13]:
sw = pd.Series([20,30,40,60,70,80,0],index = ['Mon','Tue','Wed','Tur','Fri','Sat','Sun'])
sw

Mon    20
Tue    30
Wed    40
Tur    60
Fri    70
Sat    80
Sun     0
dtype: int64

# Accessing values in data seires 

In [16]:
print(sw[1]) #Numpy Method
print(sw['Tue'])#Pandas Method
print(sw['Sun'])

30
30
0


# Accessing multipals values

In [19]:
print(sw[ [3,5] ])
print(sw[ ['Sun','Tue' ] ])

Tur    60
Sat    80
dtype: int64
Sun     0
Tue    30
dtype: int64


# Conditional selection

In [20]:
print(sw[sw>20])

Tue    30
Wed    40
Tur    60
Fri    70
Sat    80
dtype: int64


In [23]:
sw*2
print(sw)

Mon    20
Tue    30
Wed    40
Tur    60
Fri    70
Sat    80
Sun     0
dtype: int64


In [24]:
sw = sw*2
sw

Mon     40
Tue     60
Wed     80
Tur    120
Fri    140
Sat    160
Sun      0
dtype: int64

In [25]:
sw = sw/2
sw

Mon    20.0
Tue    30.0
Wed    40.0
Tur    60.0
Fri    70.0
Sat    80.0
Sun     0.0
dtype: float64

In [6]:
sw= sw//2
sw


NameError: name 'sw' is not defined

In [11]:
import numpy as np
arr = np.array([3,2,4,5,6])
ing = np.array(['a','b','c','d','e'])

In [12]:
ing

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [14]:
obj2 = pd.Series(arr,index=ing)
print(obj2)

a    3
b    2
c    4
d    5
e    6
dtype: int32


In [16]:
sdate = {"sindh":35000,"punjab":45000,"kpk":3000,"balochistan":2000}
tax_by_state= pd.Series(sdate)
print(tax_by_state)
print(tax_by_state.index)

sindh          35000
punjab         45000
kpk             3000
balochistan     2000
dtype: int64
Index(['sindh', 'punjab', 'kpk', 'balochistan'], dtype='object')


In [18]:
#changing order
sdate = {"sindh":35000,"punjab":45000,"kpk":3000,"balochistan":2000}
tax_by_state= pd.Series(sdate,index=["punjab","sindh","balochistan","kpk",])
print(tax_by_state)
print(tax_by_state.index)

punjab         45000
sindh          35000
balochistan     2000
kpk             3000
dtype: int64
Index(['punjab', 'sindh', 'balochistan', 'kpk'], dtype='object')


In [20]:
#Missing value or NaN value 
sdate = {"sindh":35000,"punjab":45000,"kpk":3000,"balochistan":2000}
tax_by_state= pd.Series(sdate,index=["punjab","sindh","balochistan","kpk","gb"])
print(tax_by_state)
print(pd.isnull(tax_by_state))

punjab         45000.0
sindh          35000.0
balochistan     2000.0
kpk             3000.0
gb                 NaN
dtype: float64
punjab         False
sindh          False
balochistan    False
kpk            False
gb              True
dtype: bool


In [21]:
#Find the missing value 
pd.isnull(tax_by_state) # Series method find the missing value
tax_by_state.isnull() # Function

punjab         False
sindh          False
balochistan    False
kpk            False
gb              True
dtype: bool

In [23]:
# Set the name
tax_by_state.name = "state tax paying capicity"
tax_by_state.index.name = "state name"
print(tax_by_state)
print(tax_by_state.index)

state name
punjab         45000.0
sindh          35000.0
balochistan     2000.0
kpk             3000.0
gb                 NaN
Name: state tax paying capicity, dtype: float64
Index(['punjab', 'sindh', 'balochistan', 'kpk', 'gb'], dtype='object', name='state name')


In [25]:
# Change the name of indexing 
print(tax_by_state)
tax_by_state.index = ['P','S','B','K','G']
print(tax_by_state)

state name
punjab         45000.0
sindh          35000.0
balochistan     2000.0
kpk             3000.0
gb                 NaN
Name: state tax paying capicity, dtype: float64
P    45000.0
S    35000.0
B     2000.0
K     3000.0
G        NaN
Name: state tax paying capicity, dtype: float64
